image: telestoworld/ci-node:latest

build:
  only:
    - master
    - staging
    - release
  script:
    - ./setupEnv.sh
    - npm install && npm run build
    - tw-lock-sync
    - cd .ci && npm install && tw-up website-builder
    - tw-sync-release && cd ..
    - tw-upload build
    - cd .ci && tw-cache-invalidation
