import { env } from 'telestoworld-commons'

export const TELO_ADDRESS = env.get('REACT_APP_TELO_TOKEN_CONTRACT_ADDRESS', '')
export const SPACE_REGISTRY_ADDRESS = env.get('REACT_APP_SPACE_REGISTRY_CONTRACT_ADDRESS', '')
export const ESTATE_REGISTRY_ADDRESS = env.get('REACT_APP_ESTATE_REGISTRY_CONTRACT_ADDRESS', '')
export const ERC721_COLLECTION_ADDRESS = env.get('REACT_APP_ERC721_COLLECTION_CONTRACT_ADDRESS', '')
export const COLLECTION_STORE_ADDRESS = env.get('REACT_APP_COLLECTION_STORE_CONTRACT_ADDRESS', '')
export const ENS_ADDRESS = env.get('REACT_APP_ENS_CONTRACT_ADDRESS', '')
export const ENS_RESOLVER_ADDRESS = env.get('REACT_APP_RESOLVER_CONTRACT_ADDRESS', '')
export const CONTROLLER_ADDRESS = env.get('REACT_APP_CONTROLLER_ADDRESS', '')
export const REGISTRAR_ADDRESS = env.get('REACT_APP_REGISTRAR_ADDRESS', '')
